apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hiteen-api.fullname" . }}-config
  labels:
    app: {{ include "hiteen-api.name" . }}
data:
  SPRINGDOC_API_DOCS_PATH: "/api-docs"
  SWAGGER_UI_PATH: "/swagger-ui"
