apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hiteen-api.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
