apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiteen-api.fullname" . }}-secret
  labels:
    app: {{ include "hiteen-api.name" . }}
type: Opaque
stringData:
  JWT_SECRET: "ac0da6c32199d5d4829ca62b05f2a353ab926e2855de718e28286ca64bc2f9df"
  REDIS_PASSWORD: "xxxxxxxx"
  POSTGRES_PASSWORD: "xxxxxxxx"
  MONGO_URI: "mongodb://hiteen:hiteen%402025@49.247.170.182:27017/hiteen?authSource=admin"
