{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiteen-admin
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app: hiteen-admin
  template:
    metadata:
      labels:
        app: hiteen-admin
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: admin
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - containerPort: 80
  {{- end }}
