apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.soketi.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.soketi.name }}
spec:
  replicas: {{ .Values.soketi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.soketi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.soketi.name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Values.soketi.name }}
          image: "{{ .Values.soketi.image.repository }}:{{ .Values.soketi.image.tag }}"
          imagePullPolicy: {{ .Values.soketi.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.soketi.service.port }}
          env:
            {{- toYaml .Values.soketi.env | nindent 12 }}
          resources:
            {{- toYaml .Values.soketi.resources | nindent 12 }}

